### PR TITLE
Fix snapshot installer

### LINKED ISSUE #46: The installer crashes after asking me where to get the snapshot.
As per https://github.com/osmosis-labs/osmosis-installer, trying to install Osmosis mainnet full node (not a validator) via the installer and after I select the option to download the pruned snapshot, I get this:

```Please choose the location nearest to your node:
1) Netherlands
2) Singapore
3) SanFrancisco (WARNING: Location usually slow)
    
Traceback (most recent call last):
  File "i.py", line 1572, in <module>
  File "i.py", line 1570, in start
  File "i.py", line 1559, in restart
  File "i.py", line 1489, in selectNetwork
  File "i.py", line 1419, in initEnvironment
  File "i.py", line 1307, in initSetup
  File "i.py", line 1145, in installLocation
  File "i.py", line 1088, in initNodeName
  File "i.py", line 1016, in setupMainnet
  File "i.py", line 956, in customPortSelection
  File "i.py", line 907, in pruningSettings
  File "i.py", line 847, in dataSyncSelection
  File "i.py", line 815, in mainNetType
  File "i.py", line 751, in mainNetLocation
AttributeError: 'NoneType' object has no attribute 'lower'
```

This happened in response to choosing 1 from the following:

```Please choose from the following options:
1) Download a snapshot from ChainLayer (recommended)
2) Start at block 1 and automatically upgrade at upgrade heights (replay from genesis, can also select rocksdb here)
3) Exit now, I only wanted to install the daemon```

### PR DESCRIPTION
**Pull request by ValarDragon**
Closes #46 

Fixes a break I introduced in #44 , Chainlayer's mirror is capitalized in their json, and thus the value in our map must be as well. (Or we figure out how to do a lowercased jq check)

I'm tested this manually on a node, for a pruned install from the netherlands. Its currently succesfully downloading the snapshot (which is where it got blocked last time)

### CODE REVIEW

**Comment by ValarDragon** [comment]
Snapshot finished downloading, and confirmed it works on my machine
